version: "3.8"
services:
  db:
    image: postgres:14-alpine
    container_name: warehouse_db
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - warehouse_db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse_app
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/warehouse
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword

volumes:
  warehouse_db_data:
